/**
 * generate_lungdev_download_data.js
 * Reads datasets_view_lungdev.csv and generates:
 *   1) src/lungdev_download_data.js  — row data array + column config
 *   2) Updates src/modules.js         — column headers
 *   3) Updates src/main.js            — render actual data
 */

const fs = require('fs');
const path = require('path');

const CSV_PATH = 'C:/Users/26693/Desktop/datasets_view_lungdev.csv';
const DATA_OUT = 'E:/网站课题/lungdev/src/lungdev_download_data.js';
const MODULES_PATH = 'E:/网站课题/lungdev/src/modules.js';
const MAIN_PATH = 'E:/网站课题/lungdev/src/main.js';

// ── 1. Parse CSV ──────────────────────────────────────────────────────────────

const csv = fs.readFileSync(CSV_PATH, 'utf8').trim();
const lines = csv.split('\n');
const headers = lines[0].split(',').map(h => h.trim());

// Helper: split CSV line respecting quotes
function splitCSVLine(line) {
  const result = [];
  let inQuotes = false;
  let current = '';
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current.trim());
  return result;
}

const rows = lines.slice(1).map((line) => {
  const vals = splitCSVLine(line);
  const row = {};
  headers.forEach((h, i) => { row[h] = vals[i] || ''; });
  return row;
});

console.log(`Parsed ${rows.length} rows from CSV`);

// ── 2. Build JS data ──────────────────────────────────────────────────────────

// Column config: maps CSV header → table header + render hint
// Drop: Number (use index+1), share (used as download URL only)
// Keep: Species, Atlas→Stage, Platform, Seq-type→Seq Method, Year, Accession, DOI, Datasets
const COLUMNS = [
  { key: 'Species',        header: 'SPECIES',     isLink: false },
  { key: 'Atlas',          header: 'STAGE',       isLink: false },
  { key: 'Tissue',         header: 'TISSUE',      isLink: false },
  { key: 'Status',         header: 'STATUS',      isLink: false },
  { key: 'Platform',       header: 'PLATFORM',    isLink: false },
  { key: 'Seq-type',       header: 'SEQ METHOD',  isLink: false },
  { key: 'Year',           header: 'YEAR',        isLink: false },
  { key: 'Accession',      header: 'ACCESSION',   isLink: true,  linkUrlKey: 'Link' },
  { key: 'DOI',            header: 'DOI',          isLink: true,  doiKey: 'Datasets' },
  { key: null,             header: 'DOWNLOAD',    isLink: false, isDownload: true },
];

// Build table rows
const tableRows = rows.map((row, idx) => {
  const cells = [];

  COLUMNS.forEach(col => {
    if (col.key === null) {
      // DOWNLOAD cell
      cells.push({
        type: 'download',
        url: row.share || '',
        label: 'Download'
      });
      return;
    }

    const rawValue = row[col.key] || '';
    const displayValue = rawValue
      .replace(/"/g, '')
      .replace(/,/g, ', ');

    if (col.isLink && col.linkUrlKey) {
      cells.push({
        type: 'link',
        value: displayValue,
        url: row[col.linkUrlKey] || ''
      });
    } else if (col.isLink && col.doiKey) {
      // Build DOI URL: https://doi.org/{DOI value from Datasets column}
      const doiRaw = row[col.doiKey] || '';
      const doiSuffix = doiRaw.split('_')[0] || doiRaw;
      const doiUrl = doiSuffix.startsWith('10.') ? `https://doi.org/${doiSuffix}` : '';
      cells.push({
        type: 'doi',
        value: displayValue,
        url: doiUrl
      });
    } else {
      cells.push({
        type: 'text',
        value: displayValue
      });
    }
  });

  return {
    id: idx + 1,
    cells
  };
});

// Generate JS string
const jsContent = `// Auto-generated by generate_lungdev_download_data.js
// Source: C:/Users/26693/Desktop/datasets_view_lungdev.csv

export const columnConfig = ${JSON.stringify(COLUMNS, null, 2)};

export const downloadRows = ${JSON.stringify(tableRows, null, 2)};

// Flat array of raw CSV rows (for reference)
export const rawRows = ${JSON.stringify(rows, null, 2)};
`;

fs.writeFileSync(DATA_OUT, jsContent, 'utf8');
console.log(`Written: ${DATA_OUT}`);

// ── 3. Update modules.js column headers ───────────────────────────────────────

const modulesContent = fs.readFileSync(MODULES_PATH, 'utf8');

// Build new thead HTML
const newTheadCells = COLUMNS.map(col =>
  `<th>${col.header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="${COLUMNS.indexOf(col)}"></th>`
).join('\n                  ');

const oldTheadPattern = /(<th>SPECIES .*?<\/th>\s*<\/tr>)/s;
const newThead = `                  <th>${COLUMNS[0].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="0"></th>
                  <th>${COLUMNS[1].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="1"></th>
                  <th>${COLUMNS[2].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="2"></th>
                  <th>${COLUMNS[3].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="3"></th>
                  <th>${COLUMNS[4].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="4"></th>
                  <th>${COLUMNS[5].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="5"></th>
                  <th>${COLUMNS[6].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="6"></th>
                  <th>${COLUMNS[7].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="7"></th>
                  <th>${COLUMNS[8].header} <input type="text" class="col-filter-input" placeholder="Filter..." data-col-filter="8"></th>
                  <th>${COLUMNS[9].header}</th>
                </tr>`;

// Replace the old header block
const updatedModules = modulesContent.replace(
  /                  <th>SPECIES <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="0"><\/th>\n                  <th>REGION <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="1"><\/th>\n                  <th>STAGE <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="2"><\/th>\n                  <th>AGE <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="3"><\/th>\n                  <th>PLATFORM <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="4"><\/th>\n                  <th>SEQ METHOD <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="5"><\/th>\n                  <th>YEAR <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="6"><\/th>\n                  <th>CELLS <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="7"><\/th>\n                  <th>DOI <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="8"><\/th>\n                  <th>ACCESSION <input type="text" class="col-filter-input" placeholder="Filter\.\.\." data-col-filter="9"><\/th>\n                  <th>DOWNLOAD<\/th>\n                <\/tr>/,
  newThead
);

fs.writeFileSync(MODULES_PATH, updatedModules, 'utf8');
console.log(`Updated column headers in: ${MODULES_PATH}`);

// ── 4. Update main.js — render actual data ───────────────────────────────────

const mainContent = fs.readFileSync(MAIN_PATH, 'utf8');

// Add import at the top (after existing imports)
const importLine = "import { columnConfig, downloadRows } from './lungdev_download_data.js';\n";

// Check if import already exists
if (!mainContent.includes("from './lungdev_download_data.js'")) {
  // Insert after first import line
  const firstImportEnd = mainContent.indexOf('\n', mainContent.indexOf('import '));
  const updatedMain = mainContent.slice(0, firstImportEnd + 1) + importLine + mainContent.slice(firstImportEnd + 1);
  fs.writeFileSync(MAIN_PATH, updatedMain, 'utf8');
  console.log(`Added import to: ${MAIN_PATH}`);
} else {
  console.log(`Import already exists in: ${MAIN_PATH}`);
}

// Replace placeholder with actual data rendering
const placeholder = `    <tr><td colspan="11" style="text-align: center; color: var(--textSecondary); padding: 40px;">No data available. Dataset content coming soon.</td></tr>`;

const newTbody = `    ${tableRows.map(row => {
  const cells = row.cells.map(cell => {
    if (cell.type === 'download') {
      return `<td><a href="${cell.url}" target="_blank" rel="noopener noreferrer" class="download-link-btn">Download</a></td>`;
    } else if (cell.type === 'link') {
      return `<td><a href="${cell.url}" target="_blank" rel="noopener noreferrer">${cell.value}</a></td>`;
    } else if (cell.type === 'doi') {
      return `<td><a href="${cell.url}" target="_blank" rel="noopener noreferrer">${cell.value}</a></td>`;
    } else {
      return `<td>${cell.value}</td>`;
    }
  }).join('');
  return `<tr>${cells}</tr>`;
}).join('\n    ')}`;

const updatedMain = fs.readFileSync(MAIN_PATH, 'utf8');
const withData = updatedMain.replace(placeholder, newTbody);

fs.writeFileSync(MAIN_PATH, withData, 'utf8');
console.log(`Updated data rendering in: ${MAIN_PATH}`);

// ── 5. Add download-link-btn CSS ─────────────────────────────────────────────

const cssPath = 'E:/网站课题/lungdev/src/styles.css';
const cssContent = fs.readFileSync(cssPath, 'utf8');

const downloadBtnCSS = `
/* Download link button style */
.download-link-btn {
  display: inline-flex;
  align-items: center;
  border-radius: 6px;
  padding: 4px 12px;
  font-size: 0.78rem;
  font-weight: 600;
  color: var(--primary, #2563eb);
  border: 1.5px solid var(--primary, #2563eb);
  text-decoration: none;
  transition: background 0.15s, color 0.15s;
  white-space: nowrap;
}
.download-link-btn:hover {
  background: var(--primary, #2563eb);
  color: #fff;
}
`;

if (!cssContent.includes('download-link-btn')) {
  fs.writeFileSync(cssPath, cssContent + downloadBtnCSS, 'utf8');
  console.log(`Added download button CSS to: ${cssPath}`);
} else {
  console.log(`Download button CSS already exists in: ${cssPath}`);
}

console.log('\nAll done! Run "npx vite build" to rebuild the site.');
